# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "maven"  # Specify Maven as the package ecosystem
    directory: "/"  # Root directory where pom.xml is located
    schedule:
      interval: "weekly"  # Dependabot will check for updates every week
    open-pull-requests-limit: 5  # Optional: Limit the number of open PRs from Dependabot
