spring.application.name=appointment-booking
management.endpoint.health.show-components=always
management.endpoint.health.show-details=always
management.endpoints.web.exposure.include=*

spring.h2.console.enabled=true

spring.datasource.url=jdbc:h2:mem:appointmentbooking;INIT=SET TIME ZONE 'UTC'
spring.datasource.username=sa
spring.datasource.password=password

spring.flyway.locations=classpath:db/migration
spring.flyway.enabled=true

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

