CREATE TABLE APPLICATION_USER (
    ID BIGINT NOT NULL PRIMARY KEY,
    VERSION INTEGER NOT NULL,
    EMAIL VARCHAR(254) NOT NULL,
    PASSWORD_HASH VARCHAR(128) NOT NULL,
    FIRST_NAME VARCHAR(255) NOT NULL,
    LAST_NAME VARCHAR(255) NOT NULL,
    CREATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LAST_UPDATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT UNIQUE_USER_EMAIL UNIQUE (EMAIL)
);

CREATE TABLE CLIENT (
    ID BIGINT NOT NULL,
    VERSION INTEGER NOT NULL,
    USER_ID BIGINT NOT NULL,
    CREATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LAST_UPDATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    FOREIGN KEY (USER_ID) REFERENCES APPLICATION_USER(ID) ON DELETE CASCADE
);

CREATE TABLE SPECIALIST (
   ID BIGINT NOT NULL,
   VERSION INTEGER NOT NULL,
   USER_ID BIGINT NOT NULL,
   CREATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   LAST_UPDATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   SPECIALIZATION VARCHAR(128) NOT NULL,
   PRIMARY KEY (ID),
   FOREIGN KEY (USER_ID) REFERENCES APPLICATION_USER(ID) ON DELETE CASCADE
);

CREATE TABLE TREATMENT (
   ID BIGINT NOT NULL,
   VERSION INTEGER NOT NULL,
   CREATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   LAST_UPDATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   NAME VARCHAR(512) NOT NULL,
   DESCRIPTION TEXT,
   DURATION_MINUTES INTEGER NOT NULL,
   SPECIALIST_ID BIGINT NOT NULL,
   PRIMARY KEY (ID),
   FOREIGN KEY (specialist_id) REFERENCES SPECIALIST(ID) ON DELETE CASCADE
);

CREATE TABLE APPOINTMENT (
    ID BIGINT NOT NULL,
    VERSION INTEGER NOT NULL,
    DATE_TIME TIMESTAMP NOT NULL,
    END_DATE_TIME TIMESTAMP NOT NULL,
    STATUS VARCHAR(32) NOT NULL DEFAULT 'SCHEDULED',
    CLIENT_ID BIGINT NOT NULL,
    TREATMENT_ID BIGINT NOT NULL,
    CREATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LAST_UPDATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT(ID) ON DELETE CASCADE,
    FOREIGN KEY (TREATMENT_ID) REFERENCES TREATMENT(ID) ON DELETE CASCADE,
    CONSTRAINT CHK_APPOINTMENT_TIME CHECK (END_DATE_TIME > DATE_TIME),
    CONSTRAINT CHK_APPOINTMENT_STATUS CHECK (STATUS IN ('SCHEDULED', 'CANCELLED', 'COMPLETED'))
);

CREATE SEQUENCE USER_SEQ START WITH 1 INCREMENT BY 100 NO CYCLE;
CREATE SEQUENCE CLIENT_SEQ START WITH 1 INCREMENT BY 100 NO CYCLE;
CREATE SEQUENCE SPECIALIST_SEQ START WITH 1 INCREMENT BY 100 NO CYCLE;
CREATE SEQUENCE TREATMENT_SEQ START WITH 1 INCREMENT BY 100 NO CYCLE;
CREATE SEQUENCE APPOINTMENT_SEQ START WITH 1 INCREMENT BY 100 NO CYCLE;


CREATE INDEX IDX_CLIENT_USER ON CLIENT(USER_ID);
CREATE INDEX IDX_SPECIALIST_USER ON SPECIALIST(USER_ID);
CREATE INDEX IDX_TREATMENT_SPECIALIST ON TREATMENT(SPECIALIST_ID);
CREATE INDEX IDX_APPOINTMENT_CLIENT ON APPOINTMENT(CLIENT_ID);
CREATE INDEX IDX_APPOINTMENT_TREATMENT ON APPOINTMENT(TREATMENT_ID);





